### ISSUE TITLE
python main_range_mcl.py problem

### ISSUE THREAD

**Issue by improve100** [PRBonn/range-mcl#1]
OS: ubuntu2004
python: Python 3.8.5
gpu: GeForce GTX 1060
drive NVIDIA-SMI 460.56       Driver Version: 460.56       CUDA Version: 11.2

$ python main_range_mcl.py
...
finished frame 1099 with time of:  7.22408e-05 s
finished frame 1100 with time of:  5.55515e-05 s
Average runtime after convergence: 0.16806003594713895
save the localization results at: ../results/demo_loc_results.npz
Exception ignored in: <function GlBuffer.__del__ at 0x7efcd4e45790>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 75, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteBuffers'
Exception ignored in: <function GlBuffer.__del__ at 0x7efcd4e45790>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 75, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteBuffers'
Exception ignored in: <function GlProgram.__del__ at 0x7efcd4e4e160>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 482, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteProgram'
Exception ignored in: <function GlTextureBuffer.__del__ at 0x7efcd4e45ca0>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 128, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteBuffers'
Exception ignored in: <function GlBuffer.__del__ at 0x7efcd4e45790>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 75, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteBuffers'
Exception ignored in: <function GlProgram.__del__ at 0x7efcd4e4e160>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 482, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteProgram'
Exception ignored in: <function GlProgram.__del__ at 0x7efcd4e4e160>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 482, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteProgram'
Exception ignored in: <function GlTexture2D.__del__ at 0x7efcd4e4c280>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 229, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteTextures'
Exception ignored in: <function GlTexture2D.__del__ at 0x7efcd4e4c280>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 229, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteTextures'
Exception ignored in: <function GlTexture2D.__del__ at 0x7efcd4e4c280>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 229, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteTextures'
Exception ignored in: <function GlFramebuffer.__del__ at 0x7efcd4e4e9d0>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 624, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteFramebuffers'
Exception ignored in: <function GlTexture2D.__del__ at 0x7efcd4e4c280>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 229, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteTextures'
Exception ignored in: <function GlTexture2D.__del__ at 0x7efcd4e4c280>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 229, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteTextures'
Exception ignored in: <function GlTexture2D.__del__ at 0x7efcd4e4c280>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 229, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteTextures'
Exception ignored in: <function GlRenderbuffer.__del__ at 0x7efcd4e4e5e0>
Traceback (most recent call last):
  File "/home/xxx/range-mcl/src/map_renderer/glow.py", line 591, in __del__
AttributeError: 'NoneType' object has no attribute 'glDeleteRenderbuffers'

**Comment by Chen-Xieyuanli** [comment]
Hey @improve100,

Thanks for using our code. 

It seems it can finish the localization but get some problem when deconstructing the GPU buffer after finishing the localization. 

Did you get the localization results?

**Comment by improve100** [comment]
I tried to run several other commands in readme, and the terminal would not automatically exit, but the result came out.
and i got the result files demo_loc_results.npz and demo_loc_results_updated.npz.

**Comment by Chen-Xieyuanli** [comment]
OK, it then finished already the localization process. The problem should be on the OpenGL glow library or the GPU side.
It never happened to me before, and I currently have no solution. 
Let's just keep this issue open and see whether we could find the solution later.
